const appName = "eMart";
const appVersion = "Version 1.0.0";
const credits = "@Tejas Kohade & Naman Damani";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const retypePass = "Retype Password";
const name = "Name";
const nameHint = "Tejas Kohade";
const passwordHint = "******";
const forgetPass = "Forget Password";
const signup = "Sign Up";
const login = "Log in";
const createNewAccount = "or, Create new Account";
const loginWith = "Login With";
const privacyPolicy = "Privacy And Policy";
const termsAndCond = "Terms And Conditions",
    alreadyHaveAccount = "Already have an account?",
    home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account",
    searchAnything = "Search Anything",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    womenDress = "Women Dresses",
    girlsWatchs = "Girls' Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys' Glasses",
    tShirt = "T-Shirt",
    girlsDress = "Girls' Dresses",
    featuredProduct = "Featured Product",
    womenClothing = "Women Clothing",
    menClothing = "Men Clothing & Fashion",
    comAccess = "Computer & Accessories",
    autoMobile = "Automobile",
    kidToys = "Kids Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellPhone = "Cellphone & Tab",
    furniture = "Furniture",
    general = 'Daily Needs';

const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller's Policy",
    returnPolicy = "Return policy",
    supportPolicy = "support Policy",
    productyoumaylike = "Products you may also Like";
const logout = "Logout";
const wishList = "My WishList", orders = "My Orders", messages = "My Messages";
const loggedin = "Logged in Successfully";
const loggedout = "Logged out Successfully";
const oldpass = "Old Password";
const newpass = "New Password";
